### ISSUE TITLE
Swap.ts refactoring

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#1107]
1. Collect all constants at header of file. 
2. Constants for time delays. 
3. Abstract status/error checks for each phase. 
4. Resume logic restructuring.

**Comment by rk16449** [comment]
regarding refactoring swapPhases0-4:

use code metrics extension in visual studio code
use an object to reduce method arguments i.e swapPhase0(object)
break methods into smaller functions, each function should do only one thing
reduce methods to ideally 10 lines or smaller

**Comment by sgershuny** [comment]
Regarding do_swap_poll:
Ideally we want a way of testing each individual phase with adjusting n_errs and n_reps

My suggestion:

Modularise each phase code and have the catch statements run on each phase rather than the whole while loop e.g. make function run_swapPhase1 that runs until the correct swapPhase 1 variables have been returned or max errs has been reached with the function catch its own errors internally. For swap phase 4 make function run_swapPhase4 that uses the different catch statements for swap Phase 4.

This should be done after Raj's requested changes are made.
