### ISSUE TITLE
[UI] No wrong password notification

### ISSUE THREAD

**Issue by MaxHillebrand** [layer2tech/mercury-wallet#1195]
When typing in a wrong password to unlock a wallet, there is no UI indication that it is wrong. Please add some hint with `wrong password`.

**Comment by rk16449** [comment]
The wallet shows me this when trying to load a wallet with an incorrect password unless you meant something else? (Only tested in windows, maybe you're on a different OS and the issue is there)
![incorrect password](https://user-images.githubusercontent.com/32778886/154315700-e055fd8a-4336-403f-b89d-bdde1f0098b9.PNG)

**Comment by rk16449** [comment]
This issue now occurs in my release wallet. The wallet load is no longer throwing an error to show the incorrect password window, will investigate further.
