### ISSUE TITLE
Error: Statechain not owned by this wallet

### ISSUE THREAD

**Issue by Mentakh** [layer2tech/mercury-wallet#1510]
When trying to withdraw one of my statecoins I received an error: "Statechain not owned by this Wallet. Incorrect proof key. And was not able to withdraw the statecoin.
I believe this error came after an unexpected shutdown of my computer while coinswapping.

I was able to fix it by restoring from my seed phrase to a new wallet. Had to add 1000 in the address gap limit while restoring (adding 100 at first didn't show any coins).
After this I could withdraw the statecoin. I did loose the coinswap history from the other coins, so keep that in mind before restoring. I could still go back to the old wallet and view the history there.

**Comment by tomt1664** [comment]
I believe that this error is due to a swap completing but the client wallet not updating the coin (due to a network issue or in your case shutdown). So the coin showing in your wallet has been transferred to someone else, and you have received a coin that you wallet doesn't know about. When you recover from seed, you then see the new coin. 

We are trying to figure out a fix for this.

**Comment by tomt1664** [comment]
Server side fix in https://github.com/commerceblock/mercury/pull/369
