### ISSUE TITLE
Withdrawal Problems - "Awaiting Withdrawal Confirmation"

### ISSUE THREAD

**Issue by Privatize0635** [layer2tech/mercury-wallet#1698]
I'm unable to withdraw to my BTC address. 

I've tried withdrawing and increasing the transaction fee but after a long "Loading Withdrawal Transaction ID..." I get a long error message. When I navigate back to my balance screen in the wallet it shows 0 BTC up top and my statecoin below (0.001 BTC denomination). I click into my statecoin and it gives me all the normal stats with "Awaiting Withdrawal Confirmation" second from the top.

At this point I'm just confused on whether the withdrawal is in progress or not. If so, when?

For further background, I've withdrawn BTC before and did not encounter any of these issues.

**Comment by tomt1664** [comment]
I believe this is caused by a bug we are working on right now. I assume that the unconfirmed withdrawal tx has not appeared in the withdrawing wallet (or show in a block explorer if you search for the address)? I believe the error message is because the withdrawl tx is not valid and will contain something like ("mandatory-script-verify-flag-failed (script failed an op_equalverify operation)"). 

If you are willing, please share the txid of the coin (you can email it to tom@commerceblock.com or send on telegram if you don't want to post it here) so we can confirm.

**Comment by Privatize0635** [comment]
That is correct, the withdrawal has not appeared in the withdrawing wallet. And yes, it shows "message\":\"non-mandatory-script-verify-flag (Script failed an OP_EQUALVERIFY operation)\"}". I'll get it over to you.

**Comment by Privatize0635** [comment]
Any updates on this issue and when it will be resolved?

**Comment by tomt1664** [comment]
We identified the cause, and the latest release of the wallet has a fix to prevent the same issue. I am still working on a function to recover the coin - in any case, your backup tx is valid, and can be used on the expiry. How long until that coin expires?

**Comment by Privatize0635** [comment]
Got it. Looks like there are 34 days left.

**Comment by tomt1664** [comment]
That coin has now expired, and the backup tx confirmed. You can access the private key or send it on to any other address by going to Settings -> Manage backup transactions. Sorry we couldn't recover it sooner.
