### ISSUE TITLE
Tor binaries packaging

### ISSUE THREAD

**Issue by lawlawlaw** [layer2tech/mercury-wallet#322]
The appropriate tor binaries should be bundled with the app so that the user does not have to install them separately.

**Comment by k9ert** [comment]
Isn't this already solved as the binaries are in the repo and i assume are packaged:
https://github.com/layer2tech/mercury-wallet/tree/master/resources

However, how are these binaries created in the first place? I'm asking because i'd love to also use them but i'm hesitating a bit as the process of how those are created is not transparent?

Can you share anything on how they are created?

**Comment by nicosey** [comment]
We packaged them locally, it was a bit messy.  We also doing the same with i2p at the moment.  We will try to publish a docker file soon, so people can replicate.

**Comment by k9ert** [comment]
Happy to help with that if you can give some rough guidance here?! E.g. which are exactly the "source-artifacts" you're extracting it from?

**Comment by nicosey** [comment]
We just build our own version of TOR statically linked.  It was a while ago, but we realise we should make this reproducible with a docker file.
